# Generated by Django 4.1.3 on 2022-11-11 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiSpecification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="API Title", max_length=255, verbose_name="title"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="API Description",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "specification",
                    models.JSONField(
                        blank=True,
                        help_text="API Specification",
                        null=True,
                        verbose_name="specification",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created At",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Updated at", verbose_name="updated at"
                    ),
                ),
            ],
            options={
                "db_table": "api_specification",
                "ordering": ["-updated_at"],
            },
        ),
    ]
