# Generated by Django 4.1.3 on 2022-11-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apispecification",
            name="specification",
            field=models.JSONField(
                blank=True,
                default={},
                help_text="API Specification",
                null=True,
                verbose_name="specification",
            ),
        ),
    ]
