# Generated by Django 4.1.3 on 2022-11-12 14:32

from django.db import migrations, models
import openapi.models


class Migration(migrations.Migration):

    dependencies = [
        ("openapi", "0003_alter_apispecification_specification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apispecification",
            name="specification",
            field=models.JSONField(
                blank=True,
                default=openapi.models.get_specification_placeholder,
                help_text="API Specification",
                null=True,
                verbose_name="specification",
            ),
        ),
    ]
