# Generated by Django 4.1.3 on 2022-11-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openapi", "0004_alter_apispecification_specification"),
    ]

    operations = [
        migrations.AddField(
            model_name="apispecification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spec_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apispecification",
            name="users",
            field=models.ManyToManyField(
                related_name="accessible_to", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
